#!/bin/sh /etc/rc.common

START=99
STOP=12

board_name() {
    [ -e /tmp/sysinfo/board_name ] && cat /tmp/sysinfo/board_name || echo "generic"
}

start() {
    local board=$(board_name)
    case "$board" in
        bdy,g98-nas)

            if ! [ -s /etc/config/g98_init_lock ]; then
# cat <<EOF > /etc/config/g98_init_lock
# true
# EOF
                echo "true"
            else
                echo "false"
            fi

            sleep 60

            if ! dmesg | grep -q "MAC_VLAN_Tag_Filter"; then
                sleep 20
            fi

            echo fe1b0000.ethernet > /sys/bus/platform/drivers/rk_gmac-dwmac/unbind
            echo fe1c0000.ethernet > /sys/bus/platform/drivers/rk_gmac-dwmac/unbind

            sleep 3

            echo fe1b0000.ethernet > /sys/bus/platform/drivers/rk_gmac-dwmac/bind
            echo fe1c0000.ethernet > /sys/bus/platform/drivers/rk_gmac-dwmac/bind

            ;;
        *)
            return 1
            ;;
    esac
}
