#!/bin/sh /etc/rc.common

START=99
STOP=12

board_name() {
    [ -e /tmp/sysinfo/board_name ] && cat /tmp/sysinfo/board_name || echo "generic"
}

start() {
    local board=$(board_name)
    case "$board" in
        bdy,g98-nas)
            ethtool -K eth0 tso off gso off gro off
            ethtool -K eth1 tso off gso off gro off
            if ! [ -s /etc/config/g98_init_lock ]; then
# cat <<EOF > /etc/config/g98_init_lock
# true
# EOF
                # rm -f /etc/config/network
                # /etc/init.d/network restart
                echo "true"
            else
                echo "false"
            fi
            ;;
        *)
            return 1
            ;;
    esac
}
